
aks_cluster = {
  aks_value = {
    resource_group_name = "pihu"
    virtual_network_name = "pihu_vnet"

    address_space        = ["10.0.0.0/16"]
    azurerm_subnet       = "snet-prod-aks-001"
    address_prefixes     = ["10.0.0.0/24"]
    subnet_name          = "snet-prod-aks-001"

    automatic_upgrade_channel           = ""
    azure_policy_enabled                = true
    cost_analysis_enabled               = false
    custom_ca_trust_certificates_base64 = []
    disk_encryption_set_id              = ""
    dns_prefix                          = "azks-cus-prod-aayu-01-dns"
    dns_prefix_private_cluster          = ""
    edge_zone                           = ""
    http_application_routing_enabled    = false
    image_cleaner_enabled               = false
    image_cleaner_interval_hours        = 168
    kubernetes_version                  = "1.30.1"
    local_account_disabled              = true
    rg_location                         = "westus"
    aks_name                            = "azks-cus-prod-aayu-01"
    node_os_upgrade_channel             = "None"
    node_resource_group                 = "rg-cus-prod-aayu-02"
    oidc_issuer_enabled                 = true
    open_service_mesh_enabled           = false
    private_cluster_enabled             = true
    private_cluster_public_fqdn_enabled = true
    private_dns_zone_id                 = "System"
    resource_group_name                 = "pihu"
    role_based_access_control_enabled   = true
    run_command_enabled                 = true
    sku_tier                            = "Free"
    # support_plan                        = ""
  
    workload_identity_enabled                     = true
    balance_similar_node_groups                   = false
    daemonset_eviction_for_empty_nodes_enabled    = false
    daemonset_eviction_for_occupied_nodes_enabled = true
    empty_bulk_delete_max                         = "10"
    expander                                      = "random"
    ignore_daemonsets_utilization_enabled         = false
    max_graceful_termination_sec                  = "600"
    max_node_provisioning_time                    = "15m"
    max_unready_nodes                             = 3
    max_unready_percentage                        = 45
    new_pod_scale_up_delay                        = "0s"
    scale_down_delay_after_add                    = "10m"
    scale_down_delay_after_delete                 = "10s"
    scale_down_delay_after_failure                = "3m"
    scale_down_unneeded                           = "10m"
    scale_down_unready                            = "20m"
    scale_down_utilization_threshold              = "0.5"
    scan_interval                                 = "10s"
    skip_nodes_with_local_storage                 = false
    skip_nodes_with_system_pods                   = true
    azure_rbac_enabled                            = true
    auto_scaling_enabled                          = true
    capacity_reservation_group_id                 = ""
    fips_enabled                                  = false
    gpu_driver                                    = ""
    gpu_instance                                  = ""
    host_encryption_enabled                       = false
    host_group_id                                 = ""
    kubelet_disk_type                             = "OS"
    max_count                                     = 5
    max_pods                                      = 60
    min_count                                     = 2
    node_pool_name                                = "akscusprd01"
    node_count                                    = 2
    node_labels                                   = {}
    node_public_ip_enabled                        = false
    node_public_ip_prefix_id                      = ""
    only_critical_addons_enabled                  = false
    orchestrator_version                          = "1.30.1"
    os_disk_size_gb                               = 128
    os_disk_type                                  = "Managed"
    os_sku                                        = "Ubuntu"
    pod_subnet_id                                 = ""
    proximity_placement_group_id                  = ""
    scale_down_mode                               = "Delete"
    snapshot_id                                   = ""
    tags                                          = {}
    temporary_name_for_rotation                   = ""
    default_node_pool_type                        = "VirtualMachineScaleSets"
    ultra_ssd_enabled                             = false
    vm_size                                       = "Standard_B2s"

    workload_runtime              = ""
    zones                         = []
    drain_timeout_in_minutes      = 0
    max_surge                     = "10%"
    node_soak_duration_in_minutes = 0
    identity_ids                  = []
    type                          = "SystemAssigned"
     dns_service_ip      = "10.20.0.10"
    ip_versions         = ["IPv4"]
    load_balancer_sku   = "standard"
    network_data_plane  = "azure"
    network_mode        = ""
    network_plugin      = "azure"
    network_plugin_mode = "overlay"
    network_policy      = ""
    outbound_type       = "loadBalancer"
    pod_cidr            = "10.244.0.0/16"
    pod_cidrs           = ["10.244.0.0/16"]
    service_cidr        = "10.20.0.0/16"
    service_cidrs       = ["10.20.0.0/16"]

    backend_pool_type                      = "NodeIPConfiguration"
    idle_timeout_in_minutes                = 4
    managed_outbound_ip_count              = 1
    managed_outbound_ipv6_count            = 0
    outbound_ip_address_ids                = []
    outbound_ip_prefix_ids                 = []
    outbound_ports_allocated               = 0
    aks_log_analytic_name                  = "aks-log-analytics-01"
    msi_auth_for_monitoring_enable         = true
    sku                                    = "PerGB2018"
    retention_in_days                      = 30
    admin_password                         = "azureuser@12345678"
    admin_username                         = "azureuser"
    license                                = ""
    app_service_name                       = "ase-cus-prob-0001"
    subnet_key                             = "aks_value"
    # allow_new_private_endpoint_connections = false
   internal_load_balancing_mode           = "Web, Publishing"
    # remote_debugging_enabled               = false
    # zone_redundant                         = false
  }
}
