

variable "aks_cluster" {
  description = "Map of AKS cluster configurations"
  type = map(object({
    virtual_network_name                = string
    address_space                       = list(string)
    subnet_name                         = string
    address_prefixes                    = list(string)
    automatic_upgrade_channel           = string
    azure_policy_enabled                = bool
    cost_analysis_enabled               = bool
  # custom_ca_trust_certificates_base64 = list(string)
    disk_encryption_set_id              = string
    dns_prefix                          = string
    dns_prefix_private_cluster          = string
    edge_zone                           = string
    http_application_routing_enabled    = bool
    image_cleaner_enabled               = bool
    image_cleaner_interval_hours        = number
    kubernetes_version                  = string
    local_account_disabled              = bool
    rg_location                         = string
    aks_name                            = string
    node_os_upgrade_channel             = string
    node_resource_group                 = string
    oidc_issuer_enabled                 = bool
    open_service_mesh_enabled           = bool
    private_cluster_enabled             = bool
    private_cluster_public_fqdn_enabled = bool
    private_dns_zone_id                 = string
    resource_group_name                 = string
    role_based_access_control_enabled   = bool
    run_command_enabled                 = bool
    sku_tier                            = string
    # support_plan                                  = string
    workload_identity_enabled                     = bool
    balance_similar_node_groups                   = bool
    daemonset_eviction_for_empty_nodes_enabled    = bool
    daemonset_eviction_for_occupied_nodes_enabled = bool
    empty_bulk_delete_max                         = string
    expander                                      = string
    ignore_daemonsets_utilization_enabled         = bool
    max_graceful_termination_sec                  = string
    max_node_provisioning_time                    = string
    max_unready_nodes                             = number
    max_unready_percentage                        = number
    new_pod_scale_up_delay                        = string
    scale_down_delay_after_add                    = string
    scale_down_delay_after_delete                 = string
    scale_down_delay_after_failure                = string
    scale_down_unneeded                           = string
    scale_down_unready                            = string
    scale_down_utilization_threshold              = string
    scan_interval                                 = string
    skip_nodes_with_local_storage                 = bool
    skip_nodes_with_system_pods                   = bool
    azure_rbac_enabled                            = bool
    # tenant_id                                     = string
    auto_scaling_enabled          = bool
    capacity_reservation_group_id = string
    fips_enabled                  = bool
   # gpu_driver                    = string
    gpu_instance                  = string
    host_encryption_enabled       = bool
    host_group_id                 = string
    kubelet_disk_type             = string
    max_count                     = number
    max_pods                      = number
    min_count                     = number
    node_pool_name                = string
    node_count                    = number
    node_labels                   = map(string)
    node_public_ip_enabled        = bool
    node_public_ip_prefix_id      = string
    only_critical_addons_enabled  = bool
    orchestrator_version          = string
    os_disk_size_gb               = number
    os_disk_type                  = string
    os_sku                        = string
    pod_subnet_id                 = string
    proximity_placement_group_id  = string
    scale_down_mode               = string
    snapshot_id                   = string
    tags                          = map(string)
    temporary_name_for_rotation   = string
    default_node_pool_type        = string
    ultra_ssd_enabled             = bool
    vm_size                       = string
    workload_runtime              = string
    zones                         = list(string)
    drain_timeout_in_minutes      = number
    max_surge                     = string
    node_soak_duration_in_minutes = number
    identity_ids                  = list(string)
    type                          = string
    # day_of_month                                  = number
    # day_of_week                                   = string
    # duration                                      = string
    # frequency                                     = string
    # interval                                      = number
    # start_date                                    = string
    # start_time                                    = string
    # utc_offset                                    = string
    # week_index                                    = string
    dns_service_ip              = string
    ip_versions                 = list(string)
    load_balancer_sku           = string
    network_data_plane          = string
    network_mode                = string
    network_plugin              = string
    network_plugin_mode         = string
    network_policy              = string
    outbound_type               = string
    pod_cidr                    = string
    pod_cidrs                   = list(string)
    service_cidr                = string
    service_cidrs               = list(string)
    backend_pool_type           = string
    idle_timeout_in_minutes     = number
    managed_outbound_ip_count   = number
    managed_outbound_ipv6_count = string
    outbound_ip_address_ids     = list(string)
    # outbound_ip_prefix_ids      = list(string)
    # outbound_ports_allocated    = number  
    aks_log_analytic_name          = string
    msi_auth_for_monitoring_enable = bool
    sku                            = string
    retention_in_days              = number
    admin_username                 = string
    admin_password                 = string
    # license        = string   
    # app_service_name                       = string
    # subnet_key                             = string
    # allow_new_private_endpoint_connections = bool
    # internal_load_balancing_mode           = string
    # remote_debugging_enabled               = bool
    # zone_redundant                         = bool
  }))
}
